### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by Tukali** [whwlsfb/BurpCrypto#19]
使用AES加密后，插件报错，具体如下
java.lang.IllegalStateException: java.security.InvalidAlgorithmParameterException: Wrong IV length: must be 16 bytes long
	at burp.aes.AesUtil.fail(AesUtil.java:83)
	at burp.aes.AesUtil.doFinal(AesUtil.java:78)
	at burp.aes.AesUtil.encrypt(AesUtil.java:51)
	at burp.aes.AesIntruderPayloadProcessor.processPayload(AesIntruderPayloadProcessor.java:26)
	at burp.utils.BurpCryptoMenuFactory.lambda$createMenuItems$1(BurpCryptoMenuFactory.java:53)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.security.InvalidAlgorithmParameterException: Wrong IV length: must be 16 bytes long
	at java.base/com.sun.crypto.provider.CipherCore.init(CipherCore.java:528)
	at java.base/com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:355)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1442)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1375)
	at burp.aes.AesUtil.doFinal(AesUtil.java:71)
	... 40 more

配置如下：
<img width="787" alt="CleanShot 2022-02-28 at 11 30 43@2x" src="https://user-images.githubusercontent.com/45891208/155919382-348d616b-c3ca-4e6e-aa21-efbc8cb1d4f3.png">

**Comment by whwlsfb** [comment]
IV的长度出现问题，请确认下密钥的格式是否正确
