### ISSUE TITLE
SM4加密算法报错

### ISSUE THREAD

**Issue by QCfan** [whwlsfb/BurpCrypto#43]
BurpSuite:2014.1.1
JDK Ver:17.0.5+9-LTS-191
无法添加SM4算法到processor，log显示
Cannot find any provider supporting SM4/ECB/NoPadding
Log:
cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: Cannot find any provider supporting SM4/ECB/NoPadding
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1034)
	at cn.hutool.crypto.CipherWrapper.<init>(CipherWrapper.java:39)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:150)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:127)
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:171)
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:146)
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:78)
	at burp.sm4.SM4Util.setConfig(SM4Util.java:22)
	at burp.sm4.SM4IntruderPayloadProcessor.<init>(SM4IntruderPayloadProcessor.java:15)
	at burp.sm4.SM4UIHandler.lambda$getPanel$1(SM4UIHandler.java:112)
        ...

**Comment by whwlsfb** [comment]
请使用openjdk，高jdk版本的oraclejdk暂时无法使用

**Comment by QCfan** [comment]
> 请使用openjdk，高jdk版本的oraclejdk暂时无法使用

测试使用openjdk 21 LTS可以正常运行，感谢。但是能详细问一下是为什么有这种情况发生么？

**Comment by whwlsfb** [comment]
推测可能是oracle jdk删减了部分加解密的provider，具体原因没有进一步跟进
