### ISSUE TITLE
m1芯片的macbook ,jdk17导入时报以下错误

### ISSUE THREAD

**Issue by chenjiewei123** [whwlsfb/BurpCrypto#49]
java.lang.IllegalArgumentException: Database directory 'BurpCrypto.ldb' does not exist and could not be created
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:163)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:83)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:80)
	at burp.ni1.c(Unknown Source)
	at burp.c59.j(Unknown Source)
	at burp.c5q.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by chenjiewei123** [comment]
师傅给看看是啥原因

**Comment by chenjiewei123** [comment]
重新编译也不能够成功

**Comment by whwlsfb** [comment]
看着像是文件权限问题导致的，我也是m芯片，是没有这个问题的
